//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadLog
    {
        public int Id { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> DownloadDate { get; set; }
        public string DownloadUserId { get; set; }
    
        public virtual ImageUpload ImageUpload { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
